name: flutterapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_polyline_points: ^0.1.0
  shared_preferences: ^0.5.6+1
  google_maps_flutter: ^0.5.21+15
  location: ^2.3.5
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0    
  cupertino_icons: ^0.1.2
  firebase_database: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
   - assets/car_icon.png
   - assets/ico.png
   - assets/location_128.png
   - assets/facebook.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Bold.ttf
          weight: 700